aliases:
  - &restore-cache
    keys:
      - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - yarn-packages-{{ .Branch }}
      - yarn-packages-master
      - yarn-packages-
  - &save-cache
    paths:
      - node_modules
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  lint-and-typecheck:
    working_directory: ~/gitty-probot-test
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run: yarn lint:ci && yarn typecheck:ci
      - store_test_results:
          path: reports/junit

  test-jest:
    working_directory: ~/gitty-probot-test
    docker:
      - image: node:9
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run: yarn test

  deploy-website:
    working_directory: ~/gitty-probot-test
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run: yarn deploy

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - lint-and-typecheck
      - test-jest
      - deploy-website
