aliases:
  - &restore-cache
    keys:
      - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - yarn-packages-{{ .Branch }}
      - yarn-packages-master
      - yarn-packages-
  - &save-cache
    paths:
      - node_modules
    key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}

version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  test-jest:
    working_directory: ~/gitty-probot-test
    docker:
      - image: node:9
    steps:
      - checkout
      - restore-cache: *restore-cache
      - run: yarn --no-progress
      - save-cache: *save-cache
      - run: yarn test:ci

# Workflows enables us to run multiple jobs in parallel
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - test-jest
